jobs:
  apples:
    source:
      type: http
      url: http://apples.com/api/apples
      method: post
      ext: json
      auth:  
        bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjAsImZvbyI6ImJhciJ9.VxZtqbzg3icdEtYS7VIhndnsmwoJnw7HNeznE5Ly174
    destination:
      type: local
      name: apples
      path: ./backups/apples
      password: mysupersecretpassword
    schedule:
      every: 1d
  bananas:
    source:
      type: local
      path: /home/bananauser/bananas
      encrypt: 4B711364F821F0DF6C1FA7F4FDDF3435B9B715B1BF5C698B0D4B65A5143CB6F9
    destination:
      type: local
      name: bananas
      path: ./backups/bananas
      password: bananaspassword
    schedule:
      after: 1h
  coconuts:
    source:
      type: http
      url: https://coconuts.com/api/coconuts
    destination:
      type: gcs_bucket
      bucket: 9b70a1a8-a725-4ec2-8073-6d5a6288ebb1-foo-bar
      name: coconuts_backup
      config: primary
      password: DLGJEg5tvfRxI/0C
    schedule:
      after: 0s
      cron: "0 1 5 * *"
